server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: inventory-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/api/v1/inventory/**
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - AuthenticationFilter
            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api/v1/customers/**
              filters:
                - AuthenticationFilter
            - id: identity-service
              uri: lb://IDENTITY-SERVICE
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - AuthenticationFilter

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    web: DEBUG

jwt:
  secret: "543926515f788fdb799310d1d259702568f70d077c025ccb5e84cf4cbcf9ca17"

management:
  endpoints:
    web:
      exposure:
        include: "gateway,health,info"
  endpoint:
    gateway:
      access: unrestricted
