server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: inventory-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/api/v1/inventory/**
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders/**
            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api/v1/customers/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "gateway,health,info"
  endpoint:
    gateway:
      access: unrestricted
